### ISSUE TITLE
TTS-Server_dev_0.6_202305281029版本，流式播放Edge-OkHttp失败

### ISSUE THREAD

**Issue by laulguo** [jing332/tts-server-android#91]
Redmi K30S Ultra MIUI12.5 Andorid11
回退版本至TTS-Server_dev_0.6_202305281005 无此问题

**Comment by DaveScream** [comment]
Me too. But author said if something dont work try to clear app data because update is big.


But even on previous version. Streaming on, external decoder - on,java http - on
There was often hangups. In log I see request but nothing after that. Need to relaunch tts to start it work again. It is not always but often so java http is not usable for now.

**Comment by laulguo** [comment]
> 

same as you...

**Comment by jing332** [comment]
Edge - Java OkHTTP 本就是实验性加入的。
如今我的电脑配置开发本项目十分吃力(全量编译需要8min, 增量编译1-3min)，所以我已经没有维护项目的兴趣，故也不会去修这个bug了，见谅。
